In [ ]:
import numpy as np

In [ ]:
x=[1,4,5,28] 
x

[1, 4, 5, 28]

In [ ]:
np.sqrt(x)

array([1.        , 2.        , 2.23606798, 5.29150262])

In [ ]:
np.log(x)

array([0.        , 1.38629436, 1.60943791, 3.33220451])

In [ ]:
np.exp(x)

array([2.71828183e+00, 5.45981500e+01, 1.48413159e+02, 1.44625706e+12])

In [ ]:
x

[1, 4, 5, 28]

In [ ]:
#Floor and Ceil 
arr1=np.array([10.8,3.64,6.6,10.2]) 
arr1

array([10.8 ,  3.64,  6.6 , 10.2 ])

In [ ]:
np.floor(arr1)

array([10.,  3.,  6., 10.])

In [ ]:
np.ceil(arr1)

array([11.,  4.,  7., 11.])

In [ ]:
np.round(arr1)

array([11.,  4.,  7., 10.])

In [ ]:
np.round(4)

4

In [ ]:
np.round(3.4)

3.0

In [ ]:
#Stacking 
#vertical stacking --  no.of columns shoud be same 
#horizontal stacking -- no.of rows should be same 

In [ ]:
arr1=np.arange(10).reshape(2,5) 
arr2=np.arange(20).reshape(4,5) 

In [ ]:
arr1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
arr2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
np.vstack((arr1,arr2))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
arr1=np.arange(10).reshape(2,5) 
arr2=np.arange(20).reshape(2,10) 
np.hstack((arr1,arr2))

array([[ 0,  1,  2,  3,  4,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [ ]:
#split 
from sklearn.model_selection import train_test_split

In [ ]:
#vertical split-- splits array vertically row wise
#horizontal split-- splits array horizontally column wise 

arr3=np.arange(100).reshape(10,10)
arr3

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [ ]:
np.vsplit(arr3,5)

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]]),
 array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]]),
 array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]]),
 array([[60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74, 75, 76, 77, 78, 79]]),
 array([[80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])]

In [ ]:
np.hsplit(arr3,2)

[array([[ 0,  1,  2,  3,  4],
        [10, 11, 12, 13, 14],
        [20, 21, 22, 23, 24],
        [30, 31, 32, 33, 34],
        [40, 41, 42, 43, 44],
        [50, 51, 52, 53, 54],
        [60, 61, 62, 63, 64],
        [70, 71, 72, 73, 74],
        [80, 81, 82, 83, 84],
        [90, 91, 92, 93, 94]]),
 array([[ 5,  6,  7,  8,  9],
        [15, 16, 17, 18, 19],
        [25, 26, 27, 28, 29],
        [35, 36, 37, 38, 39],
        [45, 46, 47, 48, 49],
        [55, 56, 57, 58, 59],
        [65, 66, 67, 68, 69],
        [75, 76, 77, 78, 79],
        [85, 86, 87, 88, 89],
        [95, 96, 97, 98, 99]])]

In [ ]:
##linspace returns evenly spaced numbers with specified intervals 
np.linspace(0,30) #start #end(it is included), and default it gives 50 elements

array([ 0.        ,  0.6122449 ,  1.2244898 ,  1.83673469,  2.44897959,
        3.06122449,  3.67346939,  4.28571429,  4.89795918,  5.51020408,
        6.12244898,  6.73469388,  7.34693878,  7.95918367,  8.57142857,
        9.18367347,  9.79591837, 10.40816327, 11.02040816, 11.63265306,
       12.24489796, 12.85714286, 13.46938776, 14.08163265, 14.69387755,
       15.30612245, 15.91836735, 16.53061224, 17.14285714, 17.75510204,
       18.36734694, 18.97959184, 19.59183673, 20.20408163, 20.81632653,
       21.42857143, 22.04081633, 22.65306122, 23.26530612, 23.87755102,
       24.48979592, 25.10204082, 25.71428571, 26.32653061, 26.93877551,
       27.55102041, 28.16326531, 28.7755102 , 29.3877551 , 30.        ])

In [ ]:
np.linspace(0,25,100)

array([ 0.        ,  0.25252525,  0.50505051,  0.75757576,  1.01010101,
        1.26262626,  1.51515152,  1.76767677,  2.02020202,  2.27272727,
        2.52525253,  2.77777778,  3.03030303,  3.28282828,  3.53535354,
        3.78787879,  4.04040404,  4.29292929,  4.54545455,  4.7979798 ,
        5.05050505,  5.3030303 ,  5.55555556,  5.80808081,  6.06060606,
        6.31313131,  6.56565657,  6.81818182,  7.07070707,  7.32323232,
        7.57575758,  7.82828283,  8.08080808,  8.33333333,  8.58585859,
        8.83838384,  9.09090909,  9.34343434,  9.5959596 ,  9.84848485,
       10.1010101 , 10.35353535, 10.60606061, 10.85858586, 11.11111111,
       11.36363636, 11.61616162, 11.86868687, 12.12121212, 12.37373737,
       12.62626263, 12.87878788, 13.13131313, 13.38383838, 13.63636364,
       13.88888889, 14.14141414, 14.39393939, 14.64646465, 14.8989899 ,
       15.15151515, 15.4040404 , 15.65656566, 15.90909091, 16.16161616,
       16.41414141, 16.66666667, 16.91919192, 17.17171717, 17.42

In [ ]:
#retstep gives the difference between 2 consecutive numbers
np.linspace(1,100,10,retstep=True)

(array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.]), 11.0)

In [ ]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.random.rand(10) #generates random numbers from 0 to 1

array([0.48311447, 0.313675  , 0.06735463, 0.86601606, 0.03452853,
       0.3197463 , 0.40703395, 0.89253131, 0.66356605, 0.34322288])

In [ ]:
#randint returns random integer from low(inclusive) to high(Exclusive) 
np.random.randint(1,100)

81

In [ ]:
np.random.randint(1,6)

5

In [ ]:
np.random.randint(1,100,10)

array([41, 49, 36, 40, 56, 87,  8, 70, 99, 54])

#PANDAS

In [ ]:
import pandas as pd 
import numpy as np

##Series

In [ ]:
s=pd.Series(np.random.rand(5)) #1D array to store data
s

0    0.442870
1    0.816935
2    0.107832
3    0.588712
4    0.967344
dtype: float64

In [ ]:
s[3]

0.5887118911730563

In [ ]:
s[0]=500 
s

0    500.000000
1      0.816935
2      0.107832
3      0.588712
4      0.967344
dtype: float64

In [ ]:
s.index=['a','b','c','d','e'] 
s

a    500.000000
b      0.816935
c      0.107832
d      0.588712
e      0.967344
dtype: float64

In [ ]:
s.index=['*','*','*','*','*']

In [ ]:
s

*    500.000000
*      0.816935
*      0.107832
*      0.588712
*      0.967344
dtype: float64

In [ ]:
s=pd.Series(np.random.rand(5),index=['a','b','c','d','e']) 
s

a    0.794810
b    0.964234
c    0.127913
d    0.052152
e    0.398704
dtype: float64

In [ ]:
s.argmin()

3

In [ ]:
s.argmax()

1

In [ ]:
s.mean()

0.4675626212412605

In [ ]:
s.median()

0.3987041879666702

In [ ]:
s.max()

0.9642337496680389

In [ ]:
s.min()

0.05215179302492279

In [ ]:
arr=np.array([1,2,3,4]) 
arr

array([1, 2, 3, 4])

In [ ]:
arr_Series=pd.Series(arr)

In [ ]:
d={'a':1,'b':2,'c':3,'d':4} 
d

{'a': 1, 'b': 2, 'c': 3, 'd': 4}

In [ ]:
pd.Series(d)

a    1
b    2
c    3
d    4
dtype: int64

##DATAFRAME

In [ ]:
import pandas as pd 
import numpy as np

In [ ]:
s=pd.Series(np.random.rand(10)) 
s

0    0.213946
1    0.511273
2    0.277730
3    0.115895
4    0.298310
5    0.632775
6    0.048733
7    0.591961
8    0.552062
9    0.557801
dtype: float64

In [ ]:
a=pd.DataFrame([s]) 
a

0         1        2         3        4         5         6  \
0  0.213946  0.511273  0.27773  0.115895  0.29831  0.632775  0.048733   

          7         8         9  
0  0.591961  0.552062  0.557801

In [ ]:
d={'age':[22,23,24],'salary':[100,1020,1040]} 
d

{'age': [22, 23, 24], 'salary': [100, 1020, 1040]}

In [ ]:
type(d)

dict

In [ ]:
data=pd.DataFrame(d) 
data

age  salary
0   22     100
1   23    1020
2   24    1040

In [ ]:
data['gender']=['Male','Female','Female'] 
data

age  salary  gender
0   22     100    Male
1   23    1020  Female
2   24    1040  Female

In [ ]:
data=[['abc',1],['def',2],['ghi',3],['hij'],['kim',5]] 
data

[['abc', 1], ['def', 2], ['ghi', 3], ['hij'], ['kim', 5]]

In [ ]:
data1=pd.DataFrame(data,columns=['A','B']) 
data1

A    B
0  abc  1.0
1  def  2.0
2  ghi  3.0
3  hij  NaN
4  kim  5.0

In [ ]:
data2=pd.DataFrame(data,index=['A','B','C','D','E']) 
data2

0    1
A  abc  1.0
B  def  2.0
C  ghi  3.0
D  hij  NaN
E  kim  5.0

In [ ]:
marks=[['priya','Maths',90],['Alex','Physics',99]] ##dict 
marks

[['priya', 'Maths', 90], ['Alex', 'Physics', 99]]

In [ ]:
d1=pd.DataFrame(marks,columns=['Name','Subject','Marks']) 
d1

Name  Subject  Marks
0  priya    Maths     90
1   Alex  Physics     99

In [ ]:
d1.rename({'marks':'Marks'},axis=1) #change modification in columns then axis=1 if change in row change then axis=0 

Name  Subject  Marks
0  priya    Maths     90
1   Alex  Physics     99

In [ ]:
d1.rename({0:'1',1:'2'},axis=0)

Name  Subject  Marks
1  priya    Maths     90
2   Alex  Physics     99

In [ ]:
data

age  salary  gender
0   22     100    Male
1   23    1020  Female
2   24    1040  Female

In [ ]:
data.iloc[:,2]

0      Male
1    Female
2    Female
Name: gender, dtype: object

In [ ]:
data.iloc[:2,1:]

salary  gender
0     100    Male
1    1020  Female

In [ ]:
data.iloc[1:,0:2]

age  salary
1   23    1020
2   24    1040

In [ ]:
data.iloc[1:,1:]

salary  gender
1    1020  Female
2    1040  Female

In [ ]:
data

age  salary  gender
0   22     100    Male
1   23    1020  Female
2   24    1040  Female

In [ ]:
data.iloc[1:,:2]

age  salary
1   23    1020
2   24    1040

In [ ]:
data.loc[:,['age','gender']]

age  gender
0   22    Male
1   23  Female
2   24  Female

In [ ]:
data.loc[:,['salary']]

salary
0     100
1    1020
2    1040

In [ ]:
data.ndim

2

In [ ]:
data.shape

(3, 3)

In [ ]:
data.columns

Index(['age', 'salary', 'gender'], dtype='object')

In [ ]:
data.values

array([[22, 100, 'Male'],
       [23, 1020, 'Female'],
       [24, 1040, 'Female']], dtype=object)

In [ ]:
data.info

<bound method DataFrame.info of    age  salary  gender
0   22     100    Male
1   23    1020  Female
2   24    1040  Female>

In [ ]:
data.dtypes

age        int64
salary     int64
gender    object
dtype: object

In [ ]:
data.describe

<bound method NDFrame.describe of    age  salary  gender
0   22     100    Male
1   23    1020  Female
2   24    1040  Female>

In [ ]:
data.isnull().sum()

age       0
salary    0
gender    0
dtype: int64

In [ ]:
data.drop('gender',axis=1)

age  salary
0   22     100
1   23    1020
2   24    1040

In [ ]:
data.duplicated()

0    False
1    False
2    False
dtype: bool

In [ ]:
data.drop_duplicates()

age  salary  gender
0   22     100    Male
1   23    1020  Female
2   24    1040  Female

#MTCARS

In [ ]:
data=pd.read_csv('/content/mtcars.csv')

In [ ]:
data

model   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  \
0             Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1   
1         Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1   
2            Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1   
3        Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0   
4     Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0   
5               Valiant  18.1    6  225.0  105  2.76  3.460  20.22   1   0   
6            Duster 360  14.3    8  360.0  245  3.21  3.570  15.84   0   0   
7             Merc 240D  24.4    4  146.7   62  3.69  3.190  20.00   1   0   
8              Merc 230  22.8    4  140.8   95  3.92  3.150  22.90   1   0   
9              Merc 280  19.2    6  167.6  123  3.92  3.440  18.30   1   0   
10            Merc 280C  17.8    6  167.6  123  3.92  3.440  18.90   1   0   
11           Merc 450SE  16.4    8  275.8  180  3.07  4.070  17.40   0   0   
12           Merc 450SL  17.3    8  275.8  180  3.07  3.730  17.60   0   0   
13          Merc 450SLC  15.2    8  275.8  180  3.07  3.780  18.00   0   0   
14   Cadillac Fleetwood  10.4    8  472.0  205  2.93  5.250  17.98   0   0   
15  Lincoln Continental  10.4    8  460.0  215  3.00  5.424  17.82   0   0   
16    Chrysler Imperial  14.7    8  440.0  230  3.23  5.345  17.42   0   0   
17             Fiat 128  32.4    4   78.7   66  4.08  2.200  19.47   1   1   
18          Honda Civic  30.4    4   75.7   52  4.93  1.615  18.52   1   1   
19       Toyota Corolla  33.9    4   71.1   65  4.22  1.835  19.90   1   1   
20        Toyota Corona  21.5    4  120.1   97  3.70  2.465  20.01   1   0   
21     Dodge Challenger  15.5    8  318.0  150  2.76  3.520  16.87   0   0   
22          AMC Javelin  15.2    8  304.0  150  3.15  3.435  17.30   0   0   
23           Camaro Z28  13.3    8  350.0  245  3.73  3.840  15.41   0   0   
24     Pontiac Firebird  19.2    8  400.0  175  3.08  3.845  17.05   0   0   
25            Fiat X1-9  27.3    4   79.0   66  4.08  1.935  18.90   1   1   
26        Porsche 914-2  26.0    4  120.3   91  4.43  2.140  16.70   0   1   
27         Lotus Europa  30.4    4   95.1  113  3.77  1.513  16.90   1   1   
28       Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.50   0   1   
29         Ferrari Dino  19.7    6  145.0  175  3.62  2.770  15.50   0   1   
30        Maserati Bora  15.0    8  301.0  335  3.54  3.570  14.60   0   1   
31           Volvo 142E  21.4    4  121.0  109  4.11  2.780  18.60   1   1   

    gear  carb  
0      4     4  
1      4     4  
2      4     1  
3      3     1  
4      3     2  
5      3     1  
6      3     4  
7      4     2  
8      4     2  
9      4     4  
10     4     4  
11     3     3  
12     3     3  
13     3     3  
14     3     4  
15     3     4  
16     3     4  
17     4     1  
18     4     2  
19     4     1  
20     3     1  
21     3     2  
22     3     2  
23     3     4  
24     3     2  
25     4     1  
26     5     2  
27     5     2  
28     5     4  
29     5     6  
30     5     8  
31     4     2

#Data Preprocession

In [ ]:
data.head()

model   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0          Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
1      Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
2         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
3     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
4  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   

   carb  
0     4  
1     4  
2     1  
3     1  
4     2

In [ ]:
data.describe()

mpg        cyl        disp          hp       drat         wt  \
count  32.000000  32.000000   32.000000   32.000000  32.000000  32.000000   
mean   20.090625   6.187500  230.721875  146.687500   3.596563   3.217250   
std     6.026948   1.785922  123.938694   68.562868   0.534679   0.978457   
min    10.400000   4.000000   71.100000   52.000000   2.760000   1.513000   
25%    15.425000   4.000000  120.825000   96.500000   3.080000   2.581250   
50%    19.200000   6.000000  196.300000  123.000000   3.695000   3.325000   
75%    22.800000   8.000000  326.000000  180.000000   3.920000   3.610000   
max    33.900000   8.000000  472.000000  335.000000   4.930000   5.424000   

            qsec         vs         am       gear     carb  
count  32.000000  32.000000  32.000000  32.000000  32.0000  
mean   17.848750   0.437500   0.406250   3.687500   2.8125  
std     1.786943   0.504016   0.498991   0.737804   1.6152  
min    14.500000   0.000000   0.000000   3.000000   1.0000  
25%    16.892500   0.000000   0.000000   3.000000   2.0000  
50%    17.710000   0.000000   0.000000   4.000000   2.0000  
75%    18.900000   1.000000   1.000000   4.000000   4.0000  
max    22.900000   1.000000   1.000000   5.000000   8.0000

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 12 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   model   32 non-null     object 
 1   mpg     32 non-null     float64
 2   cyl     32 non-null     int64  
 3   disp    32 non-null     float64
 4   hp      32 non-null     int64  
 5   drat    32 non-null     float64
 6   wt      32 non-null     float64
 7   qsec    32 non-null     float64
 8   vs      32 non-null     int64  
 9   am      32 non-null     int64  
 10  gear    32 non-null     int64  
 11  carb    32 non-null     int64  
dtypes: float64(5), int64(6), object(1)
memory usage: 3.1+ KB


In [ ]:
data.isnull().sum()

model    0
mpg      0
cyl      0
disp     0
hp       0
drat     0
wt       0
qsec     0
vs       0
am       0
gear     0
carb     0
dtype: int64

In [ ]:
data.columns

Index(['model', 'mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'vs', 'am',
       'gear', 'carb'],
      dtype='object')

In [ ]:
data.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
dtype: bool

In [ ]:
df=pd.DataFrame(data)

In [ ]:
df

model   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  \
0             Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1   
1         Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1   
2            Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1   
3        Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0   
4     Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0   
5               Valiant  18.1    6  225.0  105  2.76  3.460  20.22   1   0   
6            Duster 360  14.3    8  360.0  245  3.21  3.570  15.84   0   0   
7             Merc 240D  24.4    4  146.7   62  3.69  3.190  20.00   1   0   
8              Merc 230  22.8    4  140.8   95  3.92  3.150  22.90   1   0   
9              Merc 280  19.2    6  167.6  123  3.92  3.440  18.30   1   0   
10            Merc 280C  17.8    6  167.6  123  3.92  3.440  18.90   1   0   
11           Merc 450SE  16.4    8  275.8  180  3.07  4.070  17.40   0   0   
12           Merc 450SL  17.3    8  275.8  180  3.07  3.730  17.60   0   0   
13          Merc 450SLC  15.2    8  275.8  180  3.07  3.780  18.00   0   0   
14   Cadillac Fleetwood  10.4    8  472.0  205  2.93  5.250  17.98   0   0   
15  Lincoln Continental  10.4    8  460.0  215  3.00  5.424  17.82   0   0   
16    Chrysler Imperial  14.7    8  440.0  230  3.23  5.345  17.42   0   0   
17             Fiat 128  32.4    4   78.7   66  4.08  2.200  19.47   1   1   
18          Honda Civic  30.4    4   75.7   52  4.93  1.615  18.52   1   1   
19       Toyota Corolla  33.9    4   71.1   65  4.22  1.835  19.90   1   1   
20        Toyota Corona  21.5    4  120.1   97  3.70  2.465  20.01   1   0   
21     Dodge Challenger  15.5    8  318.0  150  2.76  3.520  16.87   0   0   
22          AMC Javelin  15.2    8  304.0  150  3.15  3.435  17.30   0   0   
23           Camaro Z28  13.3    8  350.0  245  3.73  3.840  15.41   0   0   
24     Pontiac Firebird  19.2    8  400.0  175  3.08  3.845  17.05   0   0   
25            Fiat X1-9  27.3    4   79.0   66  4.08  1.935  18.90   1   1   
26        Porsche 914-2  26.0    4  120.3   91  4.43  2.140  16.70   0   1   
27         Lotus Europa  30.4    4   95.1  113  3.77  1.513  16.90   1   1   
28       Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.50   0   1   
29         Ferrari Dino  19.7    6  145.0  175  3.62  2.770  15.50   0   1   
30        Maserati Bora  15.0    8  301.0  335  3.54  3.570  14.60   0   1   
31           Volvo 142E  21.4    4  121.0  109  4.11  2.780  18.60   1   1   

    gear  carb  
0      4     4  
1      4     4  
2      4     1  
3      3     1  
4      3     2  
5      3     1  
6      3     4  
7      4     2  
8      4     2  
9      4     4  
10     4     4  
11     3     3  
12     3     3  
13     3     3  
14     3     4  
15     3     4  
16     3     4  
17     4     1  
18     4     2  
19     4     1  
20     3     1  
21     3     2  
22     3     2  
23     3     4  
24     3     2  
25     4     1  
26     5     2  
27     5     2  
28     5     4  
29     5     6  
30     5     8  
31     4     2

In [ ]:
pwd

'/content'