##PYTHON BASICS


In [ ]:
print("Hello World")

Hello World


In [ ]:
print("Pratik")

Pratik


In [ ]:
#This is for Practice and Understand Python

####DATA TYPES

####Integer

In [ ]:
1

1

In [ ]:
5

5

In [ ]:
print(5)

5


In [ ]:
####Float

In [ ]:
print(2.5)

2.5


In [ ]:
3.1456789

3.1456789

####Boolean

In [ ]:
print(True)

True


In [ ]:
print(False)

False


####String

In [ ]:
print('India','Australia','Russia',sep='-')

India-Australia-Russia


In [ ]:
print('India','Australia','Russia',sep='/')

India/Australia/Russia


In [ ]:
print('India','Australia','Russia',sep='*')

India*Australia*Russia


####Adding Value

In [ ]:
X=50 
print(X)

50


In [ ]:
X

50

In [ ]:
y=10 
X+y

60

####Subtract Value

In [ ]:
X-y

40

In [ ]:
print(y*y) 
y 


100


10

In [ ]:
X 
y

10

In [ ]:
print(type(X))

<class 'int'>


In [ ]:
z=10.5

In [ ]:
print(type(z))

<class 'float'>


In [ ]:
w=True

In [ ]:
print(type(w))

<class 'bool'>


In [ ]:
x=int(input("Enter a value:"))

Enter a value:10


In [ ]:
x

10

In [ ]:
a=5 
b=10 
print(a+b) 
print(b-a)
print(a*b) 
print(b/a) 
print(b%a) 
print(b^a) 
print(b//a)

15
5
50
2.0
0
15
2


In [ ]:
a=25 
print(a**(1/2))

5.0


###Relational Operator

In [ ]:
a=100 
b=50 
print(a<b) 
print(a>b) 
print(a>=b) 
print(a<=b)

False
True
True
False


###Membership Operator

In [ ]:
s='python' 
print('y' in s) 
print('h' in s) 
print('z' in s)

True
True
False


###List

In [ ]:
a=["apple",25,2.5,"banana","grapes"]

In [ ]:
a

['apple', 25, 2.5, 'banana', 'grapes']

In [ ]:
len(a)

5

In [ ]:
a[0]

'apple'

In [ ]:
a[1]

25

In [ ]:
a[:-1]

['apple', 25, 2.5, 'banana']

In [ ]:
a[:]

['apple', 25, 2.5, 'banana', 'grapes']

In [ ]:
a[-1]

'grapes'

In [ ]:
a[0]=100 
a

[100, 25, 2.5, 'banana', 'grapes']

In [ ]:
a[:4]

[100, 25, 2.5, 'banana']

In [ ]:
a[1:3]

[25, 2.5]

In [ ]:
a[::-1]

['grapes', 'banana', 2.5, 25, 100]

###Tuple

In [ ]:
tup=('street','sagar',234) 
tup

('street', 'sagar', 234)

####accessing

In [ ]:
tup[0]

'street'

In [ ]:
tup[1]

'sagar'

In [ ]:
tup[1:]

('sagar', 234)

In [ ]:
tup[:2]

('street', 'sagar')

In [ ]:
###deleting 
del(tup)

In [ ]:
tup

NameError: ignored

###Sets

In [ ]:
a={1,2,3,4,5,} 
a

{1, 2, 3, 4, 5}

In [ ]:
a.add(50) 
a

{1, 2, 3, 4, 5, 50}

In [ ]:
a={1,5,6}

###Dictionary

In [ ]:
d={'Name':'Samuel','age':30} 
d

{'Name': 'Samuel', 'age': 30}

In [ ]:
d['Name']

'Samuel'

In [ ]:
d['age']

30

In [ ]:
d['age']=40 
d

{'Name': 'Samuel', 'age': 40}

In [ ]:
d.items()

dict_items([('Name', 'Samuel'), ('age', 30)])

In [ ]:
d.keys()

dict_keys(['Name', 'age'])

In [ ]:
d.values()

dict_values(['Samuel', 30])

####If Statements

In [ ]:
x=int(input("Enter a number:")) 

if x==100: 
   print("You entered my favourite number")

Enter a number:100
You entered my favourite number


In [ ]:
x=int(input("Enter a number:")) 

if x==100: 
   print("You entered my favourite number") 
else: 
  print("This is not my fav number")

Enter a number:50
This is not my fav number


In [ ]:
a=int(input("Enter the value of a: ")) 
b=int(input("Enter the value of b: ")) 

if a<b: 
  print("b is greater") 
elif a==b: 
  print("A is equal to b") 
else: 
  print("A is greater5")

Enter the value of a: 100
Enter the value of b: 0
A is greater


###Looping


####For Loop

In [ ]:
list=['Indra','Raju','Sai','John'] 
for i in list: 
  print(i)

Indra
Raju
Sai
John


In [ ]:
cars=['BMW','Audi','Mercedes','Volvo']
for i in cars: 
      print(i)

BMW
Audi
Mercedes
Volvo


In [ ]:
for i in range(10): 
  print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
for i in range(25): 
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24


###While Loop

In [ ]:
i=0
while(i<=5): 
  print(i) 
  i+=1

0
1
2
3
4
5


In [ ]:
i=0
while(i<=7):  
  i+=1  
  if i==6: 
   continue  
  print(i)#prints all the elements till condition is false and skips if condition

1
2
3
4
5
7
8


In [ ]:
i=0
while(i<=7):  
  i+=1  
  if i==6: 
   break  
  print(i)#prints all the elements till condition is true and comes out of loop

1
2
3
4
5


####While Loop With Pass

In [ ]:
i=0 
str='Cambridge' 
while(i<len(str)): 
  if str[i]=='g': 
   i=i+1 

   pass 
  print("Present Letter:",str[i]) 
  i=i+1

Present Letter: C
Present Letter: a
Present Letter: m
Present Letter: b
Present Letter: r
Present Letter: i
Present Letter: d
Present Letter: e


###Functions

In [ ]:
def getAdd(a,b): 
  sum=a+b 
  return sum

In [ ]:
getAdd(10,20)

30

In [ ]:
def func2(fname): 
  print("Good Evening "+ fname) 

In [ ]:
def areaCircle(r):
  area=3.14*r**2 
  return area

In [ ]:
areaCircle(7)

153.86

In [ ]:
def aareaRect(l,b): 
  area1=l*b 
  return area1

In [ ]:
aareaRect(2,3)

6

In [ ]:
def bmi(w,h): 
  bmi1=w/h**2
  return bmi1

In [ ]:
bmi(70,1.76)

22.59814049586777

###Lambda Functions

In [ ]:
#can accept any arguments but they can return only one value in the form of ex pression 
#lambda arguments: expression ---syntax

In [ ]:
#add 10 to an argument a 
x=lambda a: a+10 
x(20)

30

In [ ]:
x=lambda a,b: a+b 
x(50,20)

70

In [ ]:
x=lambda a,b,c: a+b+c 
print(x(20,30,40)) 

90


In [ ]:
x=lambda a,b: a-b 
x(50,20)

30

In [ ]:
x=lambda a,b: a*b 
x(50,20)

1000

In [ ]:
x=lambda a,b,c: a*b*c
x(10,1,2)

20

In [ ]:
x=lambda a,b: a/b
x(10,2)

5.0

#NUMPY

In [ ]:
import numpy as np 

In [ ]:
a=np.array([1,2,3,4,5]) 
a

array([1, 2, 3, 4, 5])

In [ ]:
a.ndim

1

In [ ]:
a=np.array([[1,2,3,4,5],[2,3,4,5,6]]) 
a

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6]])

In [ ]:
a.ndim

2

In [ ]:
a=np.array([[[1,2,3],[2,3,4],[4,5,6]]]) 
a

array([[[1, 2, 3],
        [2, 3, 4],
        [4, 5, 6]]])

In [ ]:
a.ndim

3

In [ ]:
var=np.zeros(10) 
var

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
var1=np.ones(10) 
var1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
var2=np.ones((3,4,5)) 
var2

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [ ]:
var3=np.zeros((4,2,3))
var3

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [ ]:
var=np.array([20,30,40,50,70,60]) 
var

array([20, 30, 40, 50, 70, 60])

In [ ]:
var.ndim

1

In [ ]:
#argmax is index position of max value 
var.argmax() 


4

In [ ]:
var.argmin()

0

In [ ]:
var[:2]

array([20, 30])

In [ ]:
var[1:5]

array([30, 40, 50, 70])

In [ ]:
var[:-1]

array([20, 30, 40, 50, 70])

In [ ]:
arr=np.array([1,2,3,4])

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
arr.size

4

In [ ]:
x=np.array([[1,2],[2,3],[3,4],[4,5]]) 
x

array([[1, 2],
       [2, 3],
       [3, 4],
       [4, 5]])

In [ ]:
x.ndim

2

In [ ]:
x.size

8

In [ ]:
x.dtype

dtype('int64')

In [ ]:
matrix=[[1,2,3,4],[5,6,7,8],[9,10,11,12]] 
matrix

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [ ]:
b=np.array(matrix)

In [ ]:
print(b) 
print(b.dtype)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
int64


In [ ]:
#Arange retruns evenly spaced values 
np.arange(0,11,3) #start , end spacing

array([0, 3, 6, 9])

In [ ]:
np.arange(15) #end 


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
np.arange(0,15) # start and end 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
a=np.arange(10)

In [ ]:
a.ndim

1

In [ ]:
#reshape 
a=np.arange(12) 
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
a.reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
a.reshape(6,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [ ]:
a.shape

(12,)

In [ ]:
a.max()

11

In [ ]:
b=np.arange(12).reshape(3,2,2) 
b

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])